url: https://brodiepearson.github.io
baseurl:
plugins: ['jekyll/scholar']

# Site settings
title: Brodie Pearson
email: brodie.pearson@oregonstate.edu
description: "Turbulence in the Ocean"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0099FF
  secondary: 00CCFF
  secondary-dark: 333

# pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: mailto:brodie.pearson@oregonstate.edu
  - title: twitter
    url: https://twitter.com/BrodiePearson4
  - title: github
    url: https://github.com/BrodiePearson

# Postal address (add as many lines as necessary)
address:
  - line:
  - line:

# Build settings
markdown: kramdown
permalink: pretty

# Bibliography settings
#scholar:
#  style: american-meteorological-society
#  locale: en

#  sort_by: year
#  order: ascending

#  source: ./_bibliography
#  bibliography: references.bib
#  bibliography_template: bib

#  replace_strings: true
#  join_strings:    true

#  details_dir:    bibliography
#  details_layout: bibtex.html
#  details_link:   Details

#  query: "@*"
